### ISSUE TITLE
fix empty variables in .my.cnf for apache

### ISSUE THREAD

**Issue by davidjudl** [SugarFactory/puppet-sugarcrmstack_ng#64]

**Comment by czhujer** [comment]
fixed in https://github.com/SugarFactory/puppet-sugarcrmstack_ng/commit/9dd5de0aec28a76db5d0d74348f1d7a92f6b52a3

**Comment by czhujer** [comment]
PRed to testing https://github.com/SugarFactory/puppet-sugarcrmstack_ng/pull/81

**Comment by czhujer** [comment]
PRed into master https://github.com/SugarFactory/puppet-sugarcrmstack_ng/pull/84
